services:
  vpn:
    build:
      context: vpn
    # note this means that auth needs to be run separately, cause config.env is parsed at startup
    env_file: config.env
    # so restarting is probably bad because it wont have valid keys anymore
    restart: no
    ports:
      - "1080:1080"  # SOCKS5 (microsocks)
      - "8118:8118"  # HTTP (privoxy)
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - .:/config
    networks:
      vpn-net:
        ipv4_address: 10.99.0.10


  dns:
    network_mode: "service:vpn"
    build:
      context: ./dns
    volumes:
      - ./wireguard/config:/config
    restart: unless-stopped
    depends_on:
      - vpn

  proxy:
    network_mode: "service:vpn"
    build:
      context:
        ./proxy
    restart: unless-stopped

  socks:
    network_mode: "service:vpn"
    build:
      context:
        ./socks
    restart: unless-stopped
    depends_on:
      - vpn

  heartbeat:
    network_mode: "service:vpn"
    build:
      context:
        ./heartbeat
    restart: unless-stopped
    depends_on:
      - vpn

  wireguard:
    build:
      context: wireguard
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "51820:51820/udp"
    volumes:
      - ./wireguard/config:/config
    environment:
      - VPN_CONTAINER_IP=10.99.0.10
    networks:
      vpn-net:
        ipv4_address: 10.99.0.20
    depends_on:
      - vpn
    restart: unless-stopped

networks:
  vpn-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.99.0.0/24
          gateway: 10.99.0.1
