
# although these are defined together, they're intended to be run separately i.e:
#
# - `docker compose up auth` # note not detatched, we want to see output for 2FA
# - `docker compose up vpn -d` # note detatched
services:
  vpn:
    build:
      context: vpn
    # note this means that auth needs to be run separately, cause config.env is parsed at startup
    env_file: config.env
    ports:
      - "1080:1080"  # SOCKS proxy port
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/config

  socks:
    network_mode: "service:vpn"
    build:
      context:
        ./socks
    restart: unless-stopped
    depends_on:
      - vpn

  proxy:
    network_mode: "host"
    build:
      context:
        ./proxy
    restart: unless-stopped

  heartbeat:
    network_mode: "service:vpn"
    build:
      context:
        ./heartbeat
    restart: unless-stopped
    depends_on:
      - vpn